imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.project_dir%/app/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: '%kernel.debug%'
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%env(SYMFONY_LOG)%"
            level:  info
        console:
            type:   console
            bubble: false
        sentry:
            type:   raven
            dsn:    mydsn
            level:  info
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    disable_delivery:  true
